### Health Check
GET http://localhost:7070/health
Accept: application/json

### Get All Movies
GET http://localhost:7070/movies
Accept: application/json

### Get Watched Movies
GET http://localhost:7070/movies/watched
Accept: application/json

### Get Upcoming Movies
GET http://localhost:7070/movies/upcoming
Accept: application/json


### Post New Movie (valid)
POST http://localhost:7070/movies
Content-Type: application/json
Accept: application/json

{
  "title": "Gladiator II",
  "releaseTimestamp": 2025
}



### Watch Movie (valid)
POST http://localhost:7070/movies/watch
Content-Type: application/json
Accept: application/json

{
  "title": "A Brand New Movie",
  "releaseTimestamp": 21732147200
}

### Watch Movie (invalid - missing title)
POST http://localhost:7070/movies/watch
Content-Type: application/json
Accept: application/json

{
  "releaseTimestamp": 2030
}

### Watch Movie (duplicate title -> expect 409)
POST http://localhost:7070/movies/watch
Content-Type: application/json
Accept: application/json

{
  "title": "Gladiator II",
  "releaseTimestamp": 1732147200
}

### GET /movies/watch (should return 405)
GET http://localhost:7070/movies/watch
Accept: application/json
